/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/ultimo_ii_lvt_timber_plank_floor.glb -o src/components/Timber.jsx -k -K -r public 
Author: Aaron Openshaw (https://sketchfab.com/aaronopenshaw)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ultimo-ii-lvt-timber-plank-floor-f154f2372c2542d3915496afac943429
Title: Ultimo II LVT Timber Plank Floor
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Timber(props) {
  const { nodes, materials } = useGLTF('/models/ultimo_ii_lvt_timber_plank_floor.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.002}>
          <group name="skfb_offset" position={[6775.45, 1134.32, -66.198]}>
            <group name="Object_2">
              <mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.Color_M06} />
              <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Ultimo_II_LVT_Casablanca_Oak_24983} />
              <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Wood_Cherry_Original_2} />
              <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Color_M09} />
              <lineSegments name="Object_7" geometry={nodes.Object_7.geometry} material={materials.FrontColor} />
              <lineSegments name="Object_8" geometry={nodes.Object_8.geometry} material={materials.FrontColor} />
              <lineSegments name="Object_9" geometry={nodes.Object_9.geometry} material={materials.FrontColor} />
              <lineSegments name="Object_10" geometry={nodes.Object_10.geometry} material={materials.FrontColor} />
              <lineSegments name="Object_11" geometry={nodes.Object_11.geometry} material={materials.FrontColor} />
              <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.FrontColor} />
              <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.FrontColor} />
              <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.FrontColor} />
              <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.FrontColor} />
              <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.FrontColor} />
              <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.FrontColor} />
              <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.FrontColor} />
              <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.FrontColor} />
              <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.FrontColor} />
              <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.FrontColor} />
              <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.FrontColor} />
              <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.FrontColor} />
              <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.FrontColor} />
              <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.FrontColor} />
              <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.FrontColor} />
              <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.FrontColor} />
              <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ultimo_ii_lvt_timber_plank_floor.glb')
