# Generated by Django 5.1 on 2024-08-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='gltf_model',
            field=models.FileField(blank=True, null=True, upload_to='3d_models/'),
        ),
    ]
